baseURL: https://invizus.github.io
languageCode: en-us
title: Roman - sysadmin experience
theme: PaperMod
menu:
  main:
  - identifier: about
    name: About me
    url: /about/
    weight: 10
  - identifier: notes
    name: Notes
    url: /notes/
    weight: 14
  - identifier: motivate
    name: Motivate yourself
    url: /motivate/
    weight: 15
